module.exports = function (grunt) {

    // Project configuration.
    grunt.initConfig({

        // Get package information
        pkg: grunt.file.readJSON('package.json'),

        clean: {
            dist: {
                src: ['dist']
            },
            tmp: {
                src: ['tmp']
            }
        },

        jshint: {
            gruntfile: {
                src: ['Gruntfile.js']
            },
            dist: {
                src: ['src/js/*.js']
            }
        },

        copy: {
            dist: {
                cwd: 'src',
                src: ['**', '!index.html.tpl', '!js/**', '!css/**'],
                dest: 'dist',
                expand: true
            }
        },

        uglify: {
            dist: {
                src: ['src/js/**/*.js'],
                dest: 'dist/js/script.min.js',
                options: {
                    preserveComments: false
                }
            }
        },

        // Compass compile for css
        less: {
            dist: {
                options: {
                    strictMath: true,
                    compress: true
                },
                files: {
                    'dist/css/style.min.css': 'src/css/style.less'
                }
            }
        },

        // Fetch data from APIs
        curl: {
            github: {
                src: {
                    url: 'https://api.github.com/repos/MarkBiesheuvel/markbiesheuvel.nl/commits?page=1&per_page=10',
                    method: 'GET',
                    headers: {
                        'Accept': 'application/vnd.github.v3+json',
                        'User-Agent': 'development@markbiesheuvel.nl'
                    }
                },
                dest: 'tmp/github.json'
            },
            maps: {
                src: {
                    url: 'https://maps.googleapis.com/maps/api/staticmap?size=640x200&zoom=7&markers=color%3Ablue%7Clabel%3AH%7C51.469941%2C5.472258&markers=color%3Ayellow%7Clabel%3AW%7C51.574344%2C5.137818',
                    method: 'GET'
                },
                dest: 'dist/img/maps.png'
            }
        },

        template: {
            dist: {
                options: {
                    data: function () {
                        return {
                            commits: grunt.file.readJSON('tmp/github.json')
                        };
                    }
                },
                files: {
                    'tmp/index.html': ['src/index.html.tpl']
                }
            }
        },

        // Compress HTML
        htmlmin: {
            dist: {
                options: {
                    removeComments: true,
                    collapseWhitespace: true
                },
                files: {
                    'dist/index.html': 'tmp/index.html'
                }
            }
        },

        // Watch tasks
        watch: {

            // If this file changes we need to reloaded
            // Furthermore it might be necessary to rebuild files that are generated by settings in here
            gruntfile: {
                files: ['Gruntfile.js'],
                tasks: ['jshint:gruntfile'],
                options: {
                    reload: true
                }
            },

            // Validate and compress Javascript on change
            js: {
                files: ['src/js/**/*.js'],
                tasks: ['build:js'],
                options: {
                    interrupt: true
                }
            },

            // Compile CSS on change
            css: {
                files: 'src/css/**/*.less',
                tasks: ['build:css'],
                options: {
                    interrupt: true
                }
            },

            // Compile and compress HTML on change
            html: {
                files: 'src/index.html.tpl',
                tasks: ['build:html'],
                options: {
                    interrupt: true
                }
            },

            other: {
                files: ['src/**', '!src/index.html.tpl', '!src/js/**', '!src/css/**'],
                tasks: ['copy'],
                options: {
                    interrupt: true
                }
            }
        }

    });

    // Load the plugins
    require('load-grunt-tasks')(grunt);

    grunt.registerTask(
        'build:html',
        'Compile template to HTML and compress',
        function () {

            if (!grunt.file.exists('tmp/github.json')) {
                grunt.task.run('curl:github');
            }

            grunt.task.run(['template:dist', 'htmlmin:dist']);

        }
    );

    grunt.registerTask(
        'build:js',
        'Validate and compress Javascript',
        ['jshint:dist', 'uglify:dist']
    );

    grunt.registerTask(
        'build:css',
        'Compile CSS',
        ['less:dist']
    );

    grunt.registerTask(
        'build',
        'Make a clean build',
        ['clean:dist', 'clean:tmp', 'curl:maps', 'copy:dist', 'build:html', 'build:js', 'build:css']
    );

};