module.exports = function (grunt) {

    var githubHeaders = {
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'development@markbiesheuvel.nl',
        'Time-Zone': 'Europe/Amsterdam'
    }

    // Project configuration.
    grunt.initConfig({

        // Get package information
        pkg: grunt.file.readJSON('package.json'),

        clean: {
            dist: {
                src: ['dist']
            },
            tmp: {
                src: ['tmp']
            }
        },

        jshint: {
            gruntfile: {
                src: ['Gruntfile.js']
            }
        },

        copy: {
            dist: {
                cwd: 'src',
                src: ['**', '!index.html.tpl', '!img/**', '!css/**'],
                dest: 'dist',
                expand: true
            }
        },

        // Compass compile for css
        less: {
            dist: {
                options: {
                    strictMath: true,
                    compress: true
                },
                files: {
                    'tmp/style.min.css': 'src/css/style.less'
                }
            }
        },

        base64: {
            dist: {
                files: {
                    'tmp/photo.b64': 'src/img/photo.jpg'
                }
            }
        },

        // Fetch data from APIs
        curl: {
            githubRepos: {
                src: {
                    url: 'https://api.github.com/users/MarkBiesheuvel/repos?sort=updated&page=1&per_page=4',
                    method: 'GET',
                    headers: githubHeaders
                },
                dest: 'tmp/github/repos.json'
            }
        },

        template: {
            dist: {
                options: {
                    data: function () {

                        var data = {
                            photo: grunt.file.read('tmp/photo.b64'),
                            css: grunt.file.read('tmp/style.min.css'),
                            repos: grunt.file.readJSON('tmp/github/repos.json')
                        };

                        data.repos.map(function(repo) {
                            repo.commits = grunt.file.readJSON('tmp/github/repos/' + repo.id + '.json');

                            return repo;
                        });

                        return data;
                    }
                },
                files: {
                    'tmp/index.html': ['src/index.html.tpl']
                }
            }
        },

        // Compress HTML
        htmlmin: {
            dist: {
                options: {
                    removeComments: true,
                    collapseWhitespace: true
                },
                files: {
                    'dist/index.html': 'tmp/index.html'
                }
            }
        },

        // Watch tasks
        watch: {

            // If this file changes we need to reloaded
            // Furthermore it might be necessary to rebuild files that are generated by settings in here
            gruntfile: {
                files: ['Gruntfile.js'],
                tasks: ['jshint:gruntfile'],
                options: {
                    reload: true
                }
            },

            // Validate and compress Javascript on change
            js: {
                files: ['src/js/**/*.js'],
                tasks: ['build:js'],
                options: {
                    interrupt: true,
                    livereload: true
                }
            },

            // Compile CSS on change
            css: {
                files: 'src/css/**/*.less',
                tasks: ['build:css', 'build:html'],
                options: {
                    interrupt: true,
                    livereload: true
                }
            },

            // Compile and compress HTML on change
            html: {
                files: 'src/index.html.tpl',
                tasks: ['build:html'],
                options: {
                    interrupt: true,
                    livereload: true
                }
            },

            other: {
                files: ['src/**', '!src/index.html.tpl', '!src/js/**', '!src/css/**'],
                tasks: ['copy'],
                options: {
                    interrupt: true,
                    livereload: true
                }
            }
        }

    });

    // Load the plugins
    require('load-grunt-tasks')(grunt);

    grunt.registerTask('curl:githubCommits',
        'Download commits for each repository',
        function () {

            var repos = grunt.file.readJSON('tmp/github/repos.json');

            var config = {
                curl: {}
            };
            var tasks = [];

            repos.forEach(function (repo, i) {

                var taskName = 'githubCommits' + repo.id;
                var url = repo.commits_url;

                url = url.replace('{/sha}', '');
                url += '?page=1&per_page=3';

                config.curl[taskName] = {
                    src: {
                        url: url,
                        method: 'GET',
                        headers: githubHeaders
                    },
                    dest: 'tmp/github/repos/' + repo.id + '.json'
                };

                tasks.push('curl:' + taskName);

            });

            console.log(config);

            grunt.config.merge(config);
            grunt.task.run(tasks);

        }
    );

    grunt.registerTask(
        'build:html',
        'Compile template to HTML and compress',
        function () {

            if (!grunt.file.exists('tmp/github/repos.json')) {
                grunt.task.run('curl:githubRepos');
            }

            if (!grunt.file.exists('tmp/github/repos/')) {
                grunt.task.run('curl:githubCommits');
            }

            grunt.task.run(['template:dist', 'htmlmin:dist']);
        }
    );

    grunt.registerTask(
        'build:css',
        'Compile CSS',
        ['less:dist']
    );

    grunt.registerTask(
        'build',
        'Make a clean build',
        ['clean:dist', 'clean:tmp', 'copy:dist', 'base64:dist', 'build:css', 'build:html']
    );

};