module.exports = function (grunt) {

    // Project configuration.
    grunt.initConfig({

        // Get package information
        pkg: grunt.file.readJSON('package.json'),

        clean: {
            dist: {
                src: ['dist']
            }
        },

        jshint: {
            dist: {
                src: ['src/js/*.js']
            }
        },

        copy: {
            dist: {
                cwd: 'src',
                src: ['**', '!index.html', '!js/**', '!css/**'],
                dest: 'dist',
                expand: true
            },
            bootstrap: {
                cwd: 'node_modules/bootstrap/dist',
                src: ['css/*.min.css', 'fonts/**', 'js/*.min.js'],
                dest: 'dist',
                expand: true
            },
            jquery: {
                cwd: 'node_modules/jquery/dist/cdn',
                src: ['jquery-2.1.1.min.js'],
                dest: 'dist/js',
                expand: true
            }
        },

        uglify: {
            dist: {
                src: ['src/js/**/*.js'],
                dest: 'dist/js/script.min.js',
                options: {
                    preserveComments: false
                }
            }
        },

        // Compass compile for css
        sass: {
            dist: {
                files: {
                    'dist/css/style.min.css': 'src/css/main.scss'
                },
                options: {
                    style: 'compressed'
                }
            }
        },

        // Compress HTML
        htmlmin: {
            dist: {
                options: {
                    removeComments: true,
                    collapseWhitespace: true
                },
                files: {
                    'dist/index.html': 'src/index.html'
                }
            }
        },

        // Watch tasks
        watch: {

            // If this file changes we need to reloaded
            // Furthermore it might be necessary to rebuild files that are generated by settings in here
            grunt_config: {
                files: ['Gruntfile.js'],
                tasks: ['build:dist'],
                options: {
                    reload: true
                }
            },

            // Recompile client javascript on change
            js: {
                files: ['src/js/**/*.js'],
                tasks: ['jshint:dist', 'uglify:dist'],
                options: {
                    interrupt: true
                }
            },

            // Recompile css on change
            css: {
                files: 'src/css/**/*.scss',
                tasks: ['sass:dist'],
                options: {
                    interrupt: true
                }
            },

            // Recompress html on change
            html: {
                files: 'src/index.html',
                tasks: ['htmlmin:dist'],
                options: {
                    interrupt: true
                }
            },

            other: {
                files: ['src/**', '!src/index.html', '!src/js/**', '!src/css/**'],
                tasks: ['copy'],
                options: {
                    interrupt: true
                }
            }
        }

    });

    // Load the plugins
    require('load-grunt-tasks')(grunt);

    grunt.registerTask(
        'build',
        'Makes a clean build of the client app.',
        ['clean', 'copy', 'uglify', 'sass', 'htmlmin']
    );

    grunt.registerTask(
        'default',
        'Watches all files and run the node server at the same time',
        ['concurrent:all']
    );
};